QSS Cleanups + FancyMenu for Clearlooks
lxqt/lxqt-themes pull request #118
Opened 2024-04-14 20:46 UTC by AzumaHazuki

Cleaned up the code as requested (several months ago...sorry, I genuinely did not see it!) by @stefonarch - should be ready to merge for 2.0

2024-04-14 21:17 UTC, stefonarch commented
I'm afraid we can't review this in those few remaining days now.

2024-04-14 23:45 UTC, AzumaHazuki commented
2.1 release then? I didn't realize 2.0 was coming out this soon...

2024-10-05 02:00 UTC, AzumaHazuki commented
Is there a way to just accept the dev team's lxqt-config.qss changes? My version of that file didn't do anything so there's no harm in overriding it.

2024-10-05 05:53 UTC, stefonarch commented
The file had just different contents between your version and master.
Will take a look again later, lots of files.

2024-10-19 13:46 UTC, stefonarch requested changes
* Spacer has no visible line|dots anymore
* wallpaper.cfg has to be added again

2024-10-19 13:46 UTC, stefonarch commented on themes/Clearlooks/lxqt-leave.qss
> +    border: 1px solid #aaaaaa;
Why no visible border similar to notifications?

2024-10-19 13:46 UTC, stefonarch commented on themes/Clearlooks/lxqt-panel.qss
> -    padding-right: 2px;
This makes the selected item icon in the panel menu (panel settings, close window ecc) move to the left which doesn't look fine. It's present in the original theme too, also for the mainmenu. It's probably intended but IMO color change is enough.

2024-10-19 13:46 UTC, stefonarch commented on themes/Clearlooks/lxqt-panel.qss
> +#WingMenuPlugin {
Please remove wing menu styling as it's not usable anymore from Qt 5.10 on.

2024-10-19 13:46 UTC, stefonarch commented on themes/Clearlooks/lxqt-panel.qss
> +#WingMenuPlugin:pressed {
As above

2024-10-19 13:46 UTC, stefonarch commented on themes/Clearlooks/lxqt-panel.qss
> +#WingMenuPlugin QWidget {
as above

2024-10-19 15:18 UTC, stefonarch commented on themes/Clearlooks/lxqt-panel.qss
> +    /* prevents unexpected borders/boxes on hover */
That doesn't work. Showdesktop, colorpicker, main|fancymenu, quicklaunch items have now borders on hover, while some others don't (volume, mount, brightness).

2024-10-26 15:08 UTC, AzumaHazuki commented
Okay, I think we're ready :) Removed the Wing Menu stuff, did some serious cleaning up in there to lower the verbosity, and tightened a few things up. This _should_ be good to go. I'll do similar for Leech next.

2024-10-31 20:47 UTC, stefonarch commented
Not all mentioned issues are addressed.

2025-07-13 13:31 UTC, closed without merging