Style ColorPicker,Backlight,StatusNotifier in various themes
lxqt/lxqt-themes pull request #126
Opened 2024-09-26 00:07 UTC by isf63

Relevant PRs: https://github.com/lxqt/lxqt-themes/pull/120, https://github.com/lxqt/lxqt-panel/pull/2049

Style #ColorPicker, #Backlight, and #StatusNotifier QToolButton's in various themes.

2024-09-26 18:23 UTC, stefonarch requested changes
The rest seems ok.

2024-09-26 18:27 UTC, isf63 commented
Updated.

2024-09-27 19:32 UTC, stefonarch approved these changes

2024-09-27 19:33 UTC, merged

2024-09-27 19:33 UTC, stefonarch commented
Thanks!